### ISSUE TITLE
The LLM is not working

### ISSUE THREAD

**Issue by ivarejao** [geovanesantana/gitfluence#3]
It seems like that the LLM stopped working. Here are some prompts done on the [site](https://www.gitfluence.com/)

#### Example 1
```
Q: 
> how to commit with a message
A:
>
>
```
#### Example 2
```
Q: 
> how to see history log
A:
>
>
```

Basically, all prompts provide an empty answer.

**Comment by geovanesantana** [comment]
Thanks for catching this, it was caused during openAI's change of plans, it has already been fixed.
